---
- name: Create S3 remote state bucket and vpc-n-eks dynamoDB lock table
  terraform:
    binary_path: "/home/{{ lookup('env','USER') }}/bin/terraform"
    project_path: "{{ vpc_n_eks_remote_state_terraform_dir }}"
    state:        present 
    force_init: true
  register: terraform_run
