---
# tasks file for devopsitall-prerequisite
- include: download_n_install.yml
  #- include: pip_install.yml
- include: create_user_home_bin_n_add_2_path.yml
- include: copy_bins_2_user_home_bin.yml
